Full Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/__init__.py", line 591, in snakemake
    workflow.include(
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/workflow.py", line 1173, in include
    exec(compile(code, snakefile, "exec"), self.globals)
  File "/home/jeszyman/repos/cfdna-cna/workflow/int_test.smk", line 40, in <module>
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/workflow.py", line 1173, in include
    exec(compile(code, snakefile, "exec"), self.globals)
  File "/home/jeszyman/repos/cfdna-cna/workflow/cfdna_wgs_cna.smk", line 221, in <module>
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/workflow.py", line 1300, in rule
    name = self.add_rule(
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/workflow.py", line 449, in add_rule
    raise CreateRuleException(
snakemake.exceptions.CreateRuleException: The name ichor is already used by another rule

CreateRuleException in line 107 of /home/jeszyman/repos/cfdna-cna/workflow/cfdna_wgs_cna.smk:
The name ichor is already used by another rule
  File "/home/jeszyman/repos/cfdna-cna/workflow/int_test.smk", line 34, in <module>
  File "/home/jeszyman/repos/cfdna-cna/workflow/cfdna_wgs_cna.smk", line 107, in <module>
