Full Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/__init__.py", line 591, in snakemake
    workflow.include(
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/workflow.py", line 1173, in include
    exec(compile(code, snakefile, "exec"), self.globals)
  File "/home/jeszyman/repos/cfdna-cna/workflow/int_test.smk", line 11, in <module>
KeyError: 'cfdna_cna_repo'

KeyError in line 10 of /home/jeszyman/repos/cfdna-cna/workflow/int_test.smk:
'cfdna_cna_repo'
  File "/home/jeszyman/repos/cfdna-cna/workflow/int_test.smk", line 10, in <module>
